version: '3'
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - 4321:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: dev.local

  static:
    image: nginx:alpine
    environment:
      VIRTUAL_HOST: static.local
    expose:
      - 80
      - 443
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
  frontend_dev:
    build: ./frontend
    container_name: dev
    environment:
      VIRTUAL_HOST: dev.local
    volumes:
      - ./frontend:/www
      - /www/node_modules
    expose:
      - 3000
